openapi: 3.2.0
info:
  title: Dojo Capabilities API
  version: '2026-02-27'
  description: '# Introduction


    The Dojo API is a REST API, using HTTP response codes to convey status, including successful responses and errors.'
  termsOfService: https://dojo.tech/legal/
  contact:
    name: Dojo Developer Experience Team
servers:
- url: https://api.dojo.tech
security:
- ApiKeyAuth: []
tags:
- name: Capabilities
  description: Register your REST and WebSockets endpoints.
paths:
  /epos/integrations:
    get:
      tags:
      - Capabilities
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllIntegrationsResponse'
          description: All the registered integrations for this account
      summary: Get all registered integrations
      operationId: getEposIntegrations
      x-operation-id-source: derived
  /epos/integrations/rest:
    get:
      tags:
      - Capabilities
      responses:
        '200':
          description: A list of registered REST integrations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RestIntegrationResponse'
      summary: Get registered REST integrations
      operationId: getEposIntegrationsRest
      x-operation-id-source: derived
    put:
      tags:
      - Capabilities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestIntegrationRequest'
        required: true
      summary: Register a new REST integration
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RestIntegrationResponse'
      operationId: putEposIntegrationsRest
      x-operation-id-source: derived
  /epos/integrations/ws:
    get:
      tags:
      - Capabilities
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WsIntegrationResponse'
          description: Get all the WebSocket integrations registered to this account.
      summary: Get registered WebSocket integrations
      operationId: getEposIntegrationsWs
      x-operation-id-source: derived
    put:
      tags:
      - Capabilities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WsIntegrationRequest'
        required: true
        description: Register a new WebSocket integration
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WsIntegrationResponse'
      summary: Register a new WebSocket integration
      operationId: putEposIntegrationsWs
      x-operation-id-source: derived
  /epos/integrations/dojo:
    get:
      tags:
      - Capabilities
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DojoManagedIntegrationResponse'
          description: All the dojo managed integrations registered for this account
      summary: Get epos integrations dojo
      x-summary-source: derived
      operationId: getEposIntegrationsDojo
      x-operation-id-source: derived
components:
  schemas:
    RestAuthResponse:
      description: The authentication details for REST adapters.
      required:
      - authType
      type: object
      properties:
        authType:
          description: The authentication flow that Dojo will use to make requests against this REST integration.
          enum:
          - basic
          type: string
        basic:
          $ref: '#/components/schemas/RestBasicAuthResponse'
          description: The basic auth details, configured if authType == 'basic'
      example:
        authType: basic
        basic:
          username: epos-1
    RestBasicAuthRequest:
      title: Root Type for restAuth
      description: The basic authentication request details for REST adapters.
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - username
      - password
      example:
        username: epos-1
        password: admin
    WsIntegrationRequest:
      title: Root Type for wsAdapter
      description: WebSockets request
      required:
      - capabilities
      type: object
      properties:
        capabilities:
          description: Send a WS request
          type: array
          items:
            $ref: '#/components/schemas/CapabilityRequest'
      example:
        capabilities:
        - name: GetOrder
          version: 1.0.0
        - name: RecordPayment
          version: 1.0.0
    AllIntegrationsResponse:
      description: All the integrations currently registered and active for this account.
      required:
      - restIntegrations
      - wsIntegrations
      type: object
      properties:
        wsIntegrations:
          description: All the WS integrations currently registered and active for this account.
          type: array
          items:
            $ref: '#/components/schemas/WsIntegrationResponse'
        restIntegrations:
          description: All the WS integrations currently registered and active for this account.
          type: array
          items:
            $ref: '#/components/schemas/RestIntegrationResponse'
        dojoManagedIntegrations:
          description: All the integrations managed by Dojo
          type: array
          items:
            $ref: '#/components/schemas/DojoManagedIntegrationResponse'
      example:
        wsIntegrations:
        - capabilities:
          - name: GetOrder
            version: 1.0.0
          - name: RecordOrderPayment
            version: 1.0.0
          createdAt: '2024-03-30T12:00:00Z'
        restIntegrations:
        - url: https://my-epos-backend.net/dojo/
          capabilities:
          - name: SearchOrders
            version: 1.0.0
          restAuth:
            authType: basic
            basic:
              username: epos-dojo-1
          createdAt: '2024-03-30T12:00:00Z'
    RestBasicAuthResponse:
      title: Root Type for restAuth
      description: The basic authentication response details for REST adapters.
      type: object
      properties:
        username:
          type: string
      required:
      - username
      example:
        username: epos-1
    RestIntegrationResponse:
      title: Root Type for restAdapter response
      description: REST response
      required:
      - capabilities
      - auth
      - url
      - createdAt
      type: object
      properties:
        url:
          type: string
        capabilities:
          description: Receive a response to a REST request
          type: array
          items:
            $ref: '#/components/schemas/CapabilityResponse'
        auth:
          $ref: '#/components/schemas/RestAuthResponse'
        createdAt:
          format: date-time
          type: string
      example:
        capabilities:
        - name: GetOrder
          version: 1.0.0
        - name: RecordPayment
          version: 1.0.0
        url: https://my-epos.com/orders
        auth:
          authType: basic
          basic:
            username: epos-1
        createdAt: '2024-03-30T12:00:00Z'
    DojoManagedIntegrationResponse:
      title: Root Type for dojoManagedIntegration
      description: ''
      required:
      - capabilities
      - createdAt
      type: object
      properties:
        capabilities:
          description: ''
          type: array
          items:
            $ref: '#/components/schemas/CapabilityResponse'
        createdAt:
          format: date-time
          type: string
      example:
        capabilities:
        - name: GetOrder
          version: v1
        - name: RecordPayment
          version: v1
        createdAt: '2024-03-30T12:00:00Z'
    CapabilityName:
      type: string
      description: 'The name of a capability.

        (CancelOrderById, CreateOrder, ListAreas, GetOrderById, SearchTables, HandleEvent:payment_intent.created, HandleEvent:payment_intent.status_updated, SearchOrders, GetPartyById, DeletePartyById, SearchParties, UpdatePartyById, CreateParty, GetReservationById, SearchReservations, UpdateReservationById, DeleteReservationById, CreateReservation, RecordOrderPayment, CreateOrderLock, DeleteOrderLock, ExtendOrderLock, GetOrderBill)'
    WsIntegrationResponse:
      title: Root Type for wsAdapter
      description: WebSockets response
      required:
      - capabilities
      - createdAt
      type: object
      properties:
        capabilities:
          description: Receive a response to a WS request
          type: array
          items:
            $ref: '#/components/schemas/CapabilityResponse'
        createdAt:
          format: date-time
          type: string
      example:
        capabilities:
        - name: GetOrder
          version: 1.0.0
        - name: RecordPayment
          version: 1.0.0
        createdAt: '2024-03-30T12:00:00Z'
    CapabilityResponse:
      title: Root Type for method
      description: Receive a capability response
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
      - name
      - version
      - updatedAt
      example:
        name: GetOrder
        version: 1.0.0
        updatedAt: '2024-03-30T12:00:00Z'
    RestIntegrationRequest:
      title: Root Type for restAdapter request
      description: REST request
      required:
      - capabilities
      - auth
      - url
      type: object
      properties:
        url:
          type: string
        capabilities:
          description: Send a REST request
          type: array
          items:
            $ref: '#/components/schemas/CapabilityRequest'
        auth:
          $ref: '#/components/schemas/RestAuthRequest'
      example:
        capabilities:
        - name: GetOrder
          version: 1.0.0
        - name: RecordPayment
          version: 1.0.0
        url: https://my-epos.com/orders
        auth:
          authType: basic
          basic:
            username: epos-1
            password: hunter2
    RestAuthRequest:
      description: The authentication details for REST adapters
      required:
      - authType
      type: object
      properties:
        authType:
          description: The authentication flow that Dojo will use to make requests against this REST integration
          enum:
          - basic
          type: string
        basic:
          $ref: '#/components/schemas/RestBasicAuthRequest'
          description: The basic auth details, configured if authType == 'basic'
      example:
        authType: basic
        basic:
          username: epos-1
          password: hunter2
    CapabilityRequest:
      title: Root Type for method
      description: Send a request.
      type: object
      properties:
        name:
          $ref: '#/components/schemas/CapabilityName'
        version:
          type: string
      required:
      - name
      - version
      example:
        name: GetOrder
        version: 1.0.0
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
x-tagGroups:
- name: Core payments
  tags:
  - Payment intents
  - Refunds
  - Reversal
  - Captures
  - Webhooks
  - Customers
  - Setup intents
- name: In-person payments
  tags:
  - Terminals
  - Terminal sessions
- name: Capabilities
  tags:
  - Capabilities
  - Events
